"""Add soft delete and numeric prices

Revision ID: 43e9dd65eeb2
Revises: aaf2f6e90cf6
Create Date: 2026-07-11 22:31:53.622735

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '43e9dd65eeb2'
down_revision: Union[str, None] = 'aaf2f6e90cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_listings', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('car_listings', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('car_listings', 'source',
               existing_type=postgresql.ENUM('AVITO', 'AUTORU', 'DROM', 'CARPRICE', name='sourceplatform'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('car_listings', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('car_listings', 'price_rub',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('car_listings', 'fair_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_car_listings_external_id'), table_name='car_listings')
    op.create_index(op.f('ix_car_listings_external_id'), 'car_listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_car_listings_ai_verdict'), 'car_listings', ['ai_verdict'], unique=False)
    op.create_index(op.f('ix_car_listings_created_at'), 'car_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_car_listings_is_deleted'), 'car_listings', ['is_deleted'], unique=False)
    op.create_unique_constraint('uq_listing_source', 'car_listings', ['external_id', 'source'])
    op.drop_column('car_listings', 'parsed_at')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_listings', sa.Column('parsed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint('uq_listing_source', 'car_listings', type_='unique')
    op.drop_index(op.f('ix_car_listings_is_deleted'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_created_at'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_ai_verdict'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_external_id'), table_name='car_listings')
    op.create_index(op.f('ix_car_listings_external_id'), 'car_listings', ['external_id'], unique=True)
    op.alter_column('car_listings', 'fair_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('car_listings', 'price_rub',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('car_listings', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('car_listings', 'source',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('AVITO', 'AUTORU', 'DROM', 'CARPRICE', name='sourceplatform'),
               existing_nullable=False)
    op.drop_column('car_listings', 'deleted_at')
    op.drop_column('car_listings', 'is_deleted')
    # ### end Alembic commands ###