"""Initial migration

Revision ID: aaf2f6e90cf6
Revises: 
Create Date: 2026-07-11 12:25:36.867775

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'aaf2f6e90cf6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('source', sa.Enum('AVITO', 'AUTORU', 'DROM', 'CARPRICE', name='sourceplatform'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('engine_volume', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('price_rub', sa.Float(), nullable=True),
    sa.Column('fair_price', sa.Float(), nullable=True),
    sa.Column('value_score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('seller_info', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_risks', sa.JSON(), nullable=True),
    sa.Column('ai_verdict', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_listings_brand'), 'car_listings', ['brand'], unique=False)
    op.create_index(op.f('ix_car_listings_external_id'), 'car_listings', ['external_id'], unique=True)
    op.create_index(op.f('ix_car_listings_id'), 'car_listings', ['id'], unique=False)
    op.create_index(op.f('ix_car_listings_model'), 'car_listings', ['model'], unique=False)
    op.create_index(op.f('ix_car_listings_price_rub'), 'car_listings', ['price_rub'], unique=False)
    op.create_index(op.f('ix_car_listings_region'), 'car_listings', ['region'], unique=False)
    op.create_index(op.f('ix_car_listings_source'), 'car_listings', ['source'], unique=False)
    op.create_index(op.f('ix_car_listings_vin'), 'car_listings', ['vin'], unique=False)
    op.create_index(op.f('ix_car_listings_year'), 'car_listings', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('search_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_requests_id'), 'search_requests', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_requests_id'), table_name='search_requests')
    op.drop_table('search_requests')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_car_listings_year'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_vin'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_source'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_region'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_price_rub'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_model'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_id'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_external_id'), table_name='car_listings')
    op.drop_index(op.f('ix_car_listings_brand'), table_name='car_listings')
    op.drop_table('car_listings')
    # ### end Alembic commands ###